# 1. ESSENTIAL: Initialize Environment First
exec-once = dbus-update-activation-environment --systemd --all
exec-once = systemctl --user import-environment WAYLAND_DISPLAY XDG_CURRENT_DESKTOP

# 2. Portal Restarts (Keep these here)
exec-once = systemctl --user restart xdg-desktop-portal-hyprland
exec-once = systemctl --user restart xdg-desktop-portal

# 3. Start Hypridle AFTER the environment is ready
exec-once = hypridle

# 4. Everything else
exec-once = qs -c noctalia-shell
exec-once = /usr/lib/polkit-gnome/polkit-gnome-authentication-agent-1
exec-once = wl-paste --type text --watch cliphist store
exec-once = hyprctl setcursor Bibata-Modern-Ice 32

# exec-once = elephant
# exec-once = walker --gapplication-service
