#   AUTOSTART 
#   WALLPAPER  
#   PORTALS    
#   ENV     
#   M&K    
#   TILING

exec-once = swaybg -i /home/jab/Pictures/macos_mountainlion.jpg
exec-once = hyprctl setcursor Bibata-Modern-Ice 32
exec-once = waybar &

exec-once = hypridle &
exec-once = swayosd-server & # uses ~100MB RAM
exec-once = systemctl --user start hyprpolkitagent
exec-once = /usr/bin/gnome-keyring-daemon --start --components=secrets &
# makes sure hyprportal is prioritized
# exec-once = killall -q xdg-desktop-portal-hyprland; killall -q xdg-desktop-portal; /usr/lib/xdg-desktop-portal-hyprland & /usr/lib/xdg-desktop-portal

exec-once = wl-paste --type text --watch cliphist store # Stores only text data
exec-once = wl-paste --type image --watch cliphist store # Stores only image data
exec-once = wl-clip-persist --clipboard regular

#############################
### ENVIRONMENT VARIABLES ###
#############################

env = XDG_CURRENT_DESKTOP,Hyprland
env = XDG_SESSION_TYPE,wayland
env = XDG_SESSION_DESKTOP,Hyprland

env = HYPRCURSOR_THEME,Bibata-Modern-Ice
env = HYPRCURSOR_SIZE,32
env = XCURSOR_THEME,Bibata-Modern-Ice
env = XCURSOR_SIZE,32
#https://wiki.archlinux.org/title/Dark_mode_switching
env = QT_QPA_PLATFORMTHEME=Adwaita-Dark
env = GTK_THEME=Adwaita:dark
env = GTK_APPLICATION_PREFER_DARK_THEME=1


###################
### PERMISSIONS ###
###################

# See https://wiki.hypr.land/Configuring/Permissions/
# Please note permission changes here require a Hyprland restart and are not applied on-the-fly
# for security reasons

 ecosystem {
   enforce_permissions = 1
 }

permission = /usr/(bin|local/bin)/grim, screencopy, allow
permission = /usr/(lib|libexec|lib64)/xdg-desktop-portal-hyprland, screencopy, allow
permission = /usr/(bin|local/bin)/hyprlock, screencopy, allow

# permission = /usr/(bin|local/bin)/hyprpm, plugin, allow

#############
### INPUT ###
#############

# https://wiki.hypr.land/Configuring/Variables/#input
input {
    kb_layout = us
    kb_variant =
    kb_model =
    kb_options =
    kb_rules =

    follow_mouse = 1

    sensitivity = 0 # -1.0 - 1.0, 0 means no modification.

    touchpad {
        natural_scroll = false
    }
}

dwindle {
    pseudotile = true
    preserve_split = true # You probably want this
}
master {
    new_status = master
}
