
# See https://wiki.hypr.land/Configuring/Keywords/

$browser = /home/jab/AppImages/helium.appimage
$terminal = foot
$fileManager = thunar
$launcher = /home/jab/.config/rofi/launchers/type-3/launcher.sh
# https://github.com/adi1090x/rofi?tab=readme-ov-file


###################
# HOTKEYBINDINGS  #
###################
$mainMod = SUPER # Sets winkey
bind = $mainMod SHIFT, M, exit,
bind = $mainMod, L, exec, hyprlock
bind = $mainMod, Q, killactive,
bind = $mainMod, F, fullscreen

bind = $mainMod SHIFT, R, exec, pkill waybar && exec waybar &

bind = $mainMod, E, exec, $fileManager
bind = $mainMod, 4, exec, $browser
bind = $mainMod, T, exec, $terminal
bind = $mainMod SHIFT, T, exec, [float;size 30% 35%;center] foot
bind = $mainMod, R, exec, $launcher

# replaces togglefloating with autoresizing
bind = $mainMod, G, exec, /home/jab/.config/hypr/smart_floater.sh
bind = $mainMod, Tab, cyclenext, tiled
bind = $mainMod, Space, cyclenext, floating

bind = $mainMod, 6, exec, hyprpicker -f hex
bind = $mainMod SHIFT, S, exec, sh -c 'slurp | grim -g - /home/jab/Pictures>

# bind = $mainMod, V, exec,
# bind = $mainMod, N, exec,
# bind = $mainMod, I, exec,
# bind = $mainMod SHIFT, W, exec,
# bind = $mainMod, 1, exec,
# bind = $mainMod, 2, exec,

# Move focus with mainMod + arrow keys
bind = $mainMod, a, movefocus, l
bind = $mainMod, d, movefocus, r
bind = $mainMod, w, movefocus, u
bind = $mainMod, s, movefocus, d
bind = $mainMod, Z, workspace, 1
bind = $mainMod, X, workspace, 2
bind = $mainMod, C, workspace, 3
bind = $mainMod, V, workspace, 4
bind = $mainMod SHIFT, Z, movetoworkspace, 1
bind = $mainMod SHIFT, X, movetoworkspace, 2
bind = $mainMod SHIFT, C, movetoworkspace, 3
bind = $mainMod SHIFT, V, movetoworkspace, 4
bind = $mainMod, mouse_down, workspace, e+1
bind = $mainMod, mouse_up, workspace, e-1
bindm = $mainMod, mouse:272, movewindow
bindm = $mainMod, mouse:273, resizewindow

bindel = ,XF86AudioRaiseVolume, exec, swayosd-client --output-volume 4 rais>
bindel = ,XF86AudioLowerVolume, exec, swayosd-client --output-volume -4 low>
bindel = ,XF86AudioMute, exec, swayosd-client --output-volume mute-toggle
bindel = ,XF86AudioMicMute, exec, wpctl set-mute @DEFAULT_AUDIO_SOURCE@ tog>
bindl = , XF86AudioNext, exec, playerctl next
bindl = , XF86AudioPause, exec, playerctl play-pause
bindl = , XF86AudioPlay, exec, playerctl play-pause
bindl = , XF86AudioPrev, exec, playerctl previous
