# ===============================================
# GENERAL SETTINGS
# ===============================================
$ipc = qs -c noctalia-shell ipc call
$focus = $ipc lockScreen focus
$lock = $ipc lockScreen lock

general {
    # This prevents multiple hyprlock instances from running
    lock_cmd = $lock        
    
    # Lock the session before the system goes to sleep
    before_sleep_cmd = loginctl lock-session    
    
    # Ensure display is on after waking up from sleep
    after_sleep_cmd = hyprctl dispatch dpms on; $focus  
}

# ===============================================
# LISTENER 1: LOCK SCREEN (15 Minutes)
# ===============================================
listener {
    # 900 seconds = 15 minutes
    timeout = 900                                
    
    # This triggers the 'lock_cmd' defined above
    on-timeout = loginctl lock-session           
}

# ===============================================
# LISTENER 2: DPMS OFF (17 Minutes)
# ===============================================
listener {
    # 1020 seconds = 17 minutes
    timeout = 1020                               
    
    # Turn off screen (Change HDMI-A-1 if 'hyprctl monitors' says otherwise)
    on-timeout = hyprctl dispatch dpms off       
    
    # Turn screen back on when activity is detected
    on-resume = hyprctl dispatch dpms on; $focus         
}
