##############################
### WINDOWS AND WORKSPACES ###
##############################

# Thunar
windowrule {
    name = thunar-float
    match:class = ^(Thunar)$
    float = on
}

# GTK Portal
windowrule {
    name = portal-fix
    match:class = ^(xdg-desktop-portal-gtk)$
    match:title = ^(All Files)$
    float = on
}

# Foot Terminal
# windowrule {
#     name = foot-floating
#     match:class = ^(foot)$
#     float = on
#     size = 550 490
# }

# Swayimg
windowrule {
    name = swayimg-float
    match:class = ^(swayimg)$
    float = on
}

# Global maximize suppression
windowrule {
    name = suppress-max
    match:class = .*
    suppress_event = maximize
}

# XWayland Dragging Fix
windowrule {
    name = xwayland-drag-fix
    match:class = ^$
    match:title = ^$
    match:xwayland = true
    match:float = true
    match:fullscreen = false
    match:pin = false
    no_focus = on
}

# Workspace Layout Rules (TV Mode)
windowrule {
    name = workspace-tv-clean
    match:workspace = w[tv1]
    match:float = false
    border_size = 0
    rounding = 0
}

# Workspace Layout Rules (Fullscreen/Floating state 1)
windowrule {
    name = workspace-f1-clean
    match:workspace = f[1]
    match:float = false
    border_size = 0
    rounding = 0
}
