##############################
### WINDOWS AND WORKSPACES ###
##############################

# See https://wiki.hypr.land/Configuring/Window-Rules/ for more
# See https://wiki.hypr.land/Configuring/Workspace-Rules/ for workspace rules


# Float
windowrule = float,class:^(thunar)$
# windowrule = float,class:^(foot)$
# windowrule = size 550 490,class:^(foot)$

windowrule = float,class:^(swayimg)$

# Ignore maximize requests from apps
windowrule = suppressevent maximize, class:.*

# Fix some dragging issues
windowrule = nofocus,class:^$,title:^$,xwayland:1,floating:1,fullscreen:0,pinned:0

