exec-once = qs -c noctalia-shell

# exec-once = swaybg -i /home/jab/Pictures/macos_mountainlion.jpg
exec-once = hyprctl setcursor Bibata-Modern-Ice 32
# exec-once = waybar &
exec-once = hypridle &
# exec-once = swayosd-server & # uses ~100MB RAM but looks good

exec-once = /usr/lib/polkit-gnome/polkit-gnome-authentication-agent-1
exec-once = /usr/bin/gnome-keyring-daemon --start --components=secrets &

exec-once = wl-paste --type text --watch cliphist store # Stores only text data
exec-once = wl-paste --type image --watch cliphist store # Stores only image data
exec-once = wl-clip-persist --clipboard regular

# makes sure hyprportal is prioritized
# exec-once = killall -q xdg-desktop-portal-hyprland; killall -q xdg-desktop-portal; /usr/lib/xdg-desktop-portal-hyprland & /usr/lib/xdg-desktop-portal
